couchbase:
  env:
    timeouts:
      connect: 2000
      query: 75000
      view: 75000
      key-value: 20000
      max-request-lifetime: 10000
      auto-release-after: 30000
  bootstrap-hosts: couchbase://192.163.3.152,192.168.2.62
  bucket:
  name: content
  password: password
server:
  port: 1000
  error:
    include-binding-errors: always
    include-message: always

logging:
  level:
    com:
      couchbase: DEBUG
